添加instructions

diff --git a/arm64/instructions/Makefile b/arm64/instructions/Makefile
--- a/arm64/instructions/Makefile
+++ b/arm64/instructions/Makefile
@@ -1,6 +1,15 @@
 UNAME_S := $(shell uname -s)
 ifeq ($(CROSS_COMPILE),)
-CROSS_COMPILE=arm-none-eabi-
+
+CROSS_COMPILE := $(shell if aarch64-elf-objdump -i 2>&1 | grep 'elf64-big' >/dev/null 2>&1; \
+	then echo 'aarch64-elf-'; \
+	elif aarch64-linux-gnu-objdump -i 2>&1 | grep 'elf64-big' >/dev/null 2>&1; \
+	then echo 'aarch64-linux-gnu-'; \
+	else echo "***" 1>&2; \
+	echo "*** Error: Couldn't find a riscv64 version of GCC/binutils." 1>&2; \
+	echo "*** To turn off this error, run 'gmake TOOLPREFIX= ...'." 1>&2; \
+	echo "***" 1>&2; exit 1; fi)
+
 endif
 
 # Base address to load the program
@@ -20,17 +29,18 @@ BUILD = build
 
 .PHONY: clean all dump debug qemu qemu-gdb
 
-
+# define
+CFLAGS += -DPRINTF_ALIAS_STANDARD_FUNCTION_NAMES_SOFT=1
 # -O0          		: Disable optimizations
 # -g           		: Generate debug info
 # -ffixed-r8   		: Don't touch register r8
 # -fno-builtin 		: https://stackoverflow.com/questions/54281780/what-exactly-is-fno-builtin-doing-here
 # -ffreestanding 	: https://stackoverflow.com/questions/17692428/what-is-ffreestanding-option-in-gcc
 # -mcmodel=medany   : https://gcc.gnu.org/onlinedocs/gcc/RISC-V-Options.html
-CFLAGS += -g -O0
-CFLAGS += -MD
-CFLAGS += -march=armv7-m -mcpu=cortex-m3 -mtpcs-frame
-CFLAGS += -fno-omit-frame-pointer
+CFLAGS += -g -Og
+# disable generate fpu simd instructions
+#CFLAGS += -mgeneral-regs-only
+CFLAGS += -march=armv8-a -mcpu=cortex-a57
 CFLAGS += -fno-builtin -ffreestanding
 LDFLAGS += -nostdlib
 # LDFLAGS += -L/Users/starot/bin/gcc-arm-none-eabi-10.3-2021.10/lib/gcc/arm-none-eabi/10.3.1/ -lgcc 
@@ -39,12 +49,25 @@ LDFLAGS += -nostdlib
 PROG=main
 
 # List of all *c sources
+# simple_printf no need fpu or simd
+#  src/simple_print/simple_printf.c
+
 CSRC = \
- src/test.c
+ src/print/printf.c\
+ src/uart/uart.c\
+ src/main.c
 
 #List of all *S (asm) sources
 ASRC= \
- src/start.S
+ src/start.S\
+ src/vector.S\
+ src/asm/currentEL.S\
+ src/asm/callee.S\
+ src/asm/ldr_str.S\
+ src/asm/cmp.S\
+ src/asm/adr.S\
+ src/asm/pseudo.S\
+ src/asm/macro.S
 
 TMP_OBJ += $(CSRC:.c=.o)
 TMP_OBJ += $(ASRC:.S=.o)
@@ -70,11 +93,12 @@ $(BUILD)/$(PROG).elf: $(OBJ)
 
 $(BUILD)/$(PROG).bin: $(BUILD)/$(PROG).elf
 	$(OBJCOPY) -v -O binary $^ $@
-	$(OBJDUMP) -S $(BUILD)/$(PROG).elf > $(PROG).asm
+	$(OBJDUMP) --visualize-jumps=off -S $(BUILD)/$(PROG).elf > $(PROG).asm
 	$(OBJDUMP) -t $(BUILD)/$(PROG).elf | sed '1,/SYMBOL TABLE/d; s/ .* / /; /^$$/d' > $(PROG).sym
 
 clean:
 	rm -rf build/*
+	rm -f *.asm
 	rm -f *.sym
 	rm -f *.a
 	rm -f *.o 
@@ -102,7 +126,7 @@ debug: $(BUILD)/$(PROG).bin
 
 # run in qemu
 
-QEMU = qemu-system-arm
+QEMU = qemu-system-aarch64
 
 # try to generate a unique GDB port
 GDBPORT = $(shell expr `id -u` % 5000 + 25000)
@@ -114,8 +138,13 @@ ifndef CPUS
 CPUS := 1
 endif
 
-QEMUOPTS = -M lm3s6965evb -cpu cortex-m3 -nographic -smp $(CPUS)
-
+QEMUOPTS = -M virt -cpu cortex-a57 -m 8G -nographic -smp $(CPUS)
+# enable highmem
+QEMUOPTS += -machine highmem=on
+# enable EL2
+QEMUOPTS += -machine virtualization=on
+# enable EL3
+QEMUOPTS += -machine secure=on
 
 qemu: all
 	$(QEMU) $(QEMUOPTS) -kernel $(BUILD)/$(PROG).elf
